// Auto-generated component names mapping
// This file is generated automatically. Do not edit manually.

export const componentNames = {
  avatars: ['Avatar3d01', 'Avatar3d02', 'Avatar3d03', 'Avatar3d04', 'AvatarAbstract01', 'AvatarAbstract02', 'AvatarAbstract03', 'AvatarAbstract04', 'AvatarByewind', 'AvatarDefault', 'AvatarFemale01', 'AvatarFemale02', 'AvatarFemale03', 'AvatarFemale04', 'AvatarFemale05', 'AvatarFemale06', 'AvatarMale01', 'AvatarMale02', 'AvatarMale03', 'AvatarMale04', 'AvatarMale05', 'AvatarMale06'],
  backgrounds: ['Geometric01', 'Geometric02', 'Geometric03', 'Geometric04', 'Geometric05', 'Geometric06', 'Geometric07', 'Gradient01', 'Gradient02', 'Gradient03', 'Gradient04', 'Gradient05', 'Gradient06', 'Gradient07', 'Gradient08', 'Gradient09', 'Gradient10', 'Gradient11', 'Gradient12', 'Gradient13', 'Gradient14', 'Minimal01', 'Minimal02', 'Minimal03'],
  cursors: ['CursorsBeachball', 'CursorsCross', 'CursorsDefault', 'CursorsHandGrabbing', 'CursorsHandOpen', 'CursorsHandPointing', 'CursorsMenu', 'CursorsMove', 'CursorsResizeDown', 'CursorsResizeLeft', 'CursorsResizeLeftRight', 'CursorsResizeNorthEastSouthWest', 'CursorsResizeNorthSouth', 'CursorsResizeNorthWestSouthEast', 'CursorsResizeRight', 'CursorsResizeUp', 'CursorsResizeUpDown', 'CursorsResizeWestEast', 'CursorsTextCursor', 'CursorsZoomIn', 'CursorsZoomOut'],
  emoji: ['BombEmoji', 'FaceBlowingKiss', 'FaceSteamFromNose', 'FaceTearsJoy', 'GrinningCat', 'GrinningFaceSweat', 'HeartArrow', 'HundredPoints', 'LoudlyCryingFace', 'RedHeart', 'RobotEmoji', 'SeeMonkey', 'SkullCrossbones', 'SmilingFaceHearts', 'SmilingFaceHorns', 'SmilingFaceSunglasses', 'SnowflakeEmoji', 'Snowman', 'UmbrellaEmoji', 'WinkingFace', 'WinkingFaceTongue'],
  illustrations: ['Humanoid', 'Illustration', 'Illustration01', 'Illustration02', 'Illustration03', 'Illustration04', 'Illustration05', 'Illustration06', 'Illustration07', 'Illustration08', 'Illustration09', 'Illustration10', 'Illustration11', 'Illustration12', 'Illustration13', 'Illustration14', 'Illustration15', 'Illustration16', 'Illustration17', 'Illustration18', 'Illustration19', 'Illustration20', 'Illustration21', 'Illustration22', 'Illustration23', 'Illustration24', 'Illustration25', 'Illustration26', 'Illustration27', 'Illustration28', 'LineDrawing01', 'LineDrawing02', 'LineDrawing03', 'QrCodeBig', 'Voice'],
  images: ['Image01'],
  logos: ['Android', 'AppStore', 'Apple', 'AppleIntelligence2a', 'AppleIntelligence2b', 'AppleIntelligenceA', 'AppleIntelligenceB', 'Arc', 'Behance', 'ChatGpt', 'Claude', 'Copilot', 'Discord', 'Dribbble', 'Dropbox', 'Excel', 'Facebook', 'FigmaA', 'FigmaB', 'Framer', 'Gemini', 'Github', 'Google', 'GoogleDrive', 'GooglePlay', 'Grok', 'Gumroad', 'ICloud', 'Instagram', 'LemonSqueezy', 'LinkedIn', 'Loop', 'Mastercard', 'Medium', 'Messenger', 'Meta', 'Microsoft', 'Midjourney', 'Nintendo', 'Notion', 'OneDrive', 'OneNote', 'PayPal', 'Perplexity', 'Pinterest', 'PowerPoint', 'Reddit', 'RssLogo', 'Slack', 'Snapchat', 'SnowLogo', 'Stripe', 'Telegram', 'Threads', 'TikTok', 'Twitch', 'Twitter', 'Visa', 'WhatsApp', 'Word', 'Xlogo', 'Youtube'],
} as const;

export type ComponentCategory = keyof typeof componentNames;
